# Generated by Django 5.1.1 on 2024-09-22 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionBI', '0011_alter_t_graphs_code_python'),
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='t_graph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_graphs', to='GestionBI.t_graphs'),
        ),
    ]
