# Generated by Django 5.1.1 on 2024-09-26 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionBI', '0011_alter_t_graphs_code_python'),
        ('graph', '0002_graph_t_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdata',
            name='sidebar_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_graphs', to='GestionBI.sidebaritem'),
        ),
    ]
