# Generated by Django 5.1.1 on 2024-09-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_csvdata_sidebar_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdata',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
