# Generated by Django 5.0.6 on 2024-08-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidebar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebar',
            name='height',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='sidebar',
            name='position_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sidebar',
            name='position_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sidebar',
            name='toggles',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='sidebar',
            name='width',
            field=models.IntegerField(default=250),
        ),
    ]
