# Generated by Django 5.0.6 on 2024-08-06 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='webSiteId',
        ),
        migrations.RemoveField(
            model_name='frameelement',
            name='frameId',
        ),
        migrations.AddField(
            model_name='frame',
            name='webSite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='gestionUI.website'),
        ),
        migrations.AddField(
            model_name='frameelement',
            name='frame',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='gestionUI.frame'),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cols', models.JSONField()),
                ('rows', models.JSONField()),
                ('tableStyle', models.JSONField(blank=True, null=True)),
                ('backgroundColor', models.CharField(blank=True, max_length=7, null=True)),
                ('cellStyles', models.JSONField(blank=True, null=True)),
                ('position', models.JSONField(blank=True, null=True)),
                ('paginationEnabled', models.BooleanField(default=False)),
                ('filteringEnabled', models.BooleanField(default=False)),
                ('borderVisible', models.BooleanField(default=True)),
                ('webSite', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='gestionUI.website')),
            ],
        ),
    ]
