# Generated by Django 5.0.6 on 2024-08-08 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUI', '0006_alter_image_src'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('add', 'Add'), ('delete', 'Delete'), ('update', 'Update'), ('view', 'View')], default='view', max_length=10)),
                ('style', models.JSONField(blank=True, null=True)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUI.frame')),
            ],
        ),
    ]
