# Generated by Django 5.0.6 on 2024-08-10 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUI', '0007_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='website',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionUI.website'),
        ),
        migrations.AddField(
            model_name='image',
            name='website',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionUI.website'),
        ),
        migrations.AddField(
            model_name='inputfield',
            name='website',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionUI.website'),
        ),
        migrations.AddField(
            model_name='text',
            name='website',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionUI.website'),
        ),
    ]
