# Generated by Django 5.0.6 on 2024-08-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUI', '0009_alter_button_website_alter_image_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='toggle',
            field=models.JSONField(default={'EditerEnable': False, 'isColumnDragEnabled': False, 'isDragEnabled': True, 'isRowDragEnabled': False, 'showAddColumnButton': False, 'showAddRowButton': False, 'showExportExcel': False, 'showFilteringToggle': False, 'showImportExcel': False, 'showPaginationToggle': False, 'showSelect': False}),
        ),
    ]
