# Generated by Django 5.0.6 on 2024-08-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUI', '0010_table_toggle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='toggle',
            field=models.JSONField(default={'EditerEnable': False, 'isColumnDragEnabled': False, 'isDragEnabled': True, 'isRowDragEnabled': False, 'showAddColumnButton': False, 'showAddRowButton': False, 'showCategories': False, 'showExportExcel': False, 'showFilteringToggle': False, 'showImportExcel': False, 'showPaginationToggle': False, 'showSelect': False}),
        ),
    ]
