# Generated by Django 5.0.6 on 2024-08-14 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionUI', '0009_alter_button_website_alter_image_website_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='database.category')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='gestionUI.website')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='database.category')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('INTEGER', 'Integer'), ('DATE', 'Date'), ('BOOLEAN', 'Boolean'), ('LIST', 'List'), ('IMAGE', 'Image'), ('DECIMAL', 'Decimal')], default='TEXT', max_length=50)),
                ('list_values', models.JSONField(blank=True, default=list, null=True)),
                ('referedFieldId', models.IntegerField(blank=True, null=True)),
                ('is_foreign_key', models.BooleanField(blank=True, default=False, null=True)),
                ('relatedField', models.CharField(blank=True, max_length=100, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='database.table')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.JSONField()),
                ('real_table_id', models.IntegerField(blank=True, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='database.table')),
            ],
        ),
        migrations.CreateModel(
            name='Visuals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data', models.JSONField(default=list)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('selectedFields', models.JSONField(blank=True, default=None, null=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visuals', to='gestionUI.website')),
            ],
        ),
    ]
