# Generated by Django 5.1.6 on 2025-02-21 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_website_category_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='webSite',
            new_name='website',
        ),
    ]
