# Generated by Django 5.1.6 on 2025-03-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_rename_website_category_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
