# Generated by Django 5.1.6 on 2025-03-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_field_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
