# Generated by Django 5.1.6 on 2025-03-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
