# Generated by Django 5.0.6 on 2024-08-19 16:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsibleRealisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsibleValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='T_Documents',
            fields=[
                ('Document_Id', models.AutoField(primary_key=True, serialize=False)),
                ('User_Submitter', models.CharField(max_length=255, unique=True)),
                ('Document_Name', models.CharField(max_length=255)),
                ('Document', models.FileField(null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'xlsx', 'xls', 'pptx', 'ppt', 'txt', 'jpg', 'png', 'jpeg'])])),
            ],
        ),
        migrations.CreateModel(
            name='T_Actions',
            fields=[
                ('Action_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Action_Name', models.CharField(max_length=255)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Date_Submission_Real', models.DateField(blank=True, default=None, null=True)),
                ('Date_Submission_Estimated', models.DateField(blank=True, default=None, null=True)),
                ('Date_Validation_Real', models.DateField(blank=True, default=None, null=True)),
                ('Date_Validation_Estimated', models.DateField(blank=True, default=None, null=True)),
                ('Responsible_Realisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionBI.responsiblerealisation')),
                ('Responsible_Validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionBI.responsiblevalidation')),
                ('Documents_Submission', models.ManyToManyField(blank=True, related_name='action_submission', to='GestionBI.t_documents')),
                ('Documents_Validation', models.ManyToManyField(blank=True, related_name='action_validation', to='GestionBI.t_documents')),
            ],
        ),
        migrations.CreateModel(
            name='T_Decision',
            fields=[
                ('Decision_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Decision_Name', models.CharField(max_length=255)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Actions', models.ManyToManyField(blank=True, related_name='actions to be taken+', to='GestionBI.t_actions')),
            ],
        ),
        migrations.AddField(
            model_name='responsiblevalidation',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='validation_documents', to='GestionBI.t_documents'),
        ),
        migrations.AddField(
            model_name='responsiblerealisation',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='realisation_documents', to='GestionBI.t_documents'),
        ),
        migrations.CreateModel(
            name='T_python_code',
            fields=[
                ('Code_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Code', models.TextField()),
                ('File_Name', models.CharField(default='No Name', max_length=255, unique=True)),
                ('newCodeIsPrincipal', models.BooleanField(default=True)),
                ('Causes', models.ManyToManyField(blank=True, related_name='causes of the graphs+', to='GestionBI.t_python_code')),
                ('Consequences', models.ManyToManyField(blank=True, related_name='Consequences of the graphs+', to='GestionBI.t_python_code')),
                ('Related_Code', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related graph+', to='GestionBI.t_python_code')),
            ],
        ),
        migrations.CreateModel(
            name='T_graphs',
            fields=[
                ('Img_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Img_Name', models.CharField(max_length=255, unique=True)),
                ('x_position', models.FloatField(blank=True, default=None, null=True)),
                ('y_position', models.FloatField(blank=True, default=None, null=True)),
                ('Code_Python', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GestionBI.t_python_code')),
            ],
        ),
        migrations.CreateModel(
            name='T_Report',
            fields=[
                ('report_Id', models.AutoField(primary_key=True, serialize=False)),
                ('report_Name', models.CharField(max_length=255)),
                ('Content', models.TextField(blank=True, null=True)),
                ('Decisions', models.ManyToManyField(blank=True, related_name='decisions taken+', to='GestionBI.t_decision')),
            ],
        ),
        migrations.AddField(
            model_name='t_python_code',
            name='Reports',
            field=models.ManyToManyField(blank=True, related_name='reports of the graph+', to='GestionBI.t_report'),
        ),
    ]
