# Generated by Django 5.0.6 on 2024-08-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionBI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_documents',
            name='User_Submitter',
            field=models.CharField(max_length=255),
        ),
    ]
