# Generated by Django 5.0.6 on 2024-08-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionBI', '0003_sidebar_sidebaritem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidebaritem',
            name='sidebar',
        ),
        migrations.RemoveField(
            model_name='sidebaritem',
            name='linked_sidebar',
        ),
        migrations.RemoveField(
            model_name='sidebaritem',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Sidebar',
        ),
        migrations.DeleteModel(
            name='SidebarItem',
        ),
    ]
