# Generated by Django 5.0.6 on 2024-08-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionBI', '0004_remove_sidebaritem_sidebar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_graphs',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_graphs',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
