# Generated by Django 5.0.6 on 2024-08-22 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionBI', '0005_t_graphs_height_t_graphs_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('style', models.CharField(max_length=255)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=250)),
                ('height', models.IntegerField(default=600)),
                ('toggles', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SidebarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('order', models.CharField(max_length=255)),
                ('linked_sidebar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_items', to='GestionBI.sidebar')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='GestionBI.sidebaritem')),
                ('sidebar', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='GestionBI.sidebar')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
