# Generated by Django 5.0.6 on 2024-08-25 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionBI', '0008_remove_sidebar_website_sidebaritem_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_graphs',
            name='sidebar_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graphs', to='GestionBI.sidebaritem'),
        ),
    ]
