# Generated by Django 5.0.6 on 2024-08-26 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionBI', '0009_t_graphs_sidebar_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_graphs',
            name='Code_Python',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionBI.t_python_code'),
        ),
    ]
