# Generated by Django 5.0.6 on 2024-08-29 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionBI', '0010_alter_t_graphs_code_python'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_graphs',
            name='Code_Python',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='GestionBI.t_python_code'),
            preserve_default=False,
        ),
    ]
