# Generated by Django 5.1.1 on 2024-12-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionBI', '0011_alter_t_graphs_code_python'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sidebar_item_id', models.CharField(max_length=255)),
                ('column', models.CharField(max_length=255)),
                ('unique_values', models.JSONField()),
                ('selected_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('date', 'Date'), ('number', 'Number'), ('string', 'String')], default='string', max_length=50)),
            ],
        ),
    ]
