# Generated by Django 5.1.1 on 2024-12-01 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionBI', '0012_selectedsegment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selectedsegment',
            old_name='selected_file_id',
            new_name='selectedFileId',
        ),
        migrations.RenameField(
            model_name='selectedsegment',
            old_name='sidebar_item_id',
            new_name='selectedSidebarItem',
        ),
        migrations.RenameField(
            model_name='selectedsegment',
            old_name='unique_values',
            new_name='uniqueValues',
        ),
    ]
