# Generated by Django 5.1.1 on 2024-12-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionBI', '0013_rename_selected_file_id_selectedsegment_selectedfileid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedsegment',
            name='unique_values_selected',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
